apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: team-c
  name: team-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-c-app
  namespace: team-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-c-app
  template:
    metadata:
      labels:
        app: team-c-app
    spec:
      containers:
      - name: hello-kubernetes
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: This is Team C Application deployed via Azure Arc123!
---
apiVersion: v1
kind: Service
metadata:
  name: team-c-app
  namespace: team-c
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: team-c-app
